### PR TITLE
Shard up metric

### PR DESCRIPTION
**Pull request by michaelschiff**
This change is [Reviewable](https://reviewable.io/reviews/gazette/core/281)

### CODE REVIEW

**Review by jgraettinger — COMMENTED** [review]
Looks awesome, thanks! Just a couple of nits and then I'll merge.

> *[Reviewable](https://reviewable.io/reviews/gazette/core/281#-:-MGPU7ry37Bo9qRJ_pPN:b203ppy)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @michaelschiff)

___
*[consumer/interfaces.go, line 19 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPTSNl386e7-_KSwyP:-MGPTSNm2G2Jp_NoBwPr:bja9n66) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/interfaces.go#L19)):*
> ```Go
> import (
> 	"context"
> 	"github.com/prometheus/client_golang/prometheus"
> ```

nit: there's a convention within the project to separate std library packages (above the break) from everything else (below).
___
*[consumer/resolver.go, line 6 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPTeEeBfb-65FQKMw6:-MGPTeEeBfb-65FQKMw7:b-uwtab4) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/resolver.go#L6)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/prometheus/client_golang/prometheus"
> ```

nit: move below the break please.
___
*[consumer/resolver.go, line 47 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPTkj58erA4QFxmn1n:-MGPTkj58erA4QFxmn1o:b-l4lf16) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/resolver.go#L47)):*
> ```Go
> 	state.KS.Observers = append(state.KS.Observers, r.updateLocalShards, r.updateJournalsIndex)
> 	state.KS.Mu.Unlock()
> 	prometheus.MustRegister(r)
> ```

nit: The choice to register seems like the concern of the caller and even the main(), not the Resolver itself. How about relocating to https://github.com/gazette/core/blob/master/mainboilerplate/runconsumer/run_consumer.go#L149 , eg as 

```
// Register Resolver as a prometheus.Collector for tracking shard status.
prometheus.MustRegister(service.Resolver)
```

**Review by jgraettinger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @michaelschiff)

___
*[consumer/resolver.go, line 380 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPWYHIBKBqOXSjUZuA:-MGPWYHIBKBqOXSjUZuB:b8d0cow) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/resolver.go#L380)):*
> ```Go
> 	defer r.state.KS.Mu.RUnlock()
> 	for shardID, shard := range r.shards {
> 		status := shard.resolved.assignment.Decoded.(allocator.Assignment).AssignmentValue.(pc.ReplicaStatus)
> ```

Oh, the AssignmentValue is actually a `*pc.ReplicaStatus`, not `pc.ReplicaStatus`. Mind adding or updating an existing test to provide some coverage of `Collect`?

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jgraettinger)

___
*[consumer/resolver.go, line 380 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPWYHIBKBqOXSjUZuA:-MGPijg1-O9T3MRWx5_d:b-8hm3uk) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/resolver.go#L380)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Oh, the AssignmentValue is actually a `*pc.ReplicaStatus`, not `pc.ReplicaStatus`. Mind adding or updating an existing test to provide some coverage of `Collect`?
</blockquote></details>

good catch, will add test cases for Collect
___
*[consumer/resolver.go, line 386 at r1](https://reviewable.io/reviews/gazette/core/281#-MGPXMZfBJCPATxMF5AE:-MGPiixC1pucoRafV7wX:b-thazcz) ([raw file](https://github.com/gazette/core/blob/e506803267a9457deff08bc3cd50570f2419367c/consumer/resolver.go#L386)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Oh, and you actually want the status.code.String() -- status itself will return a big blob of text protobuf. See:

https://github.com/gazette/core/blob/master/consumer/protocol/protocol.proto#L222
</blockquote></details>

ah thanks

**Review by jgraettinger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @michaelschiff)

___
*[consumer/resolver_test.go, line 7 at r2](https://reviewable.io/reviews/gazette/core/281#-MGUu3nPClRf7DiCjHXv:-MGUu3nPClRf7DiCjHXw:bbuzy9e) ([raw file](https://github.com/gazette/core/blob/cef37f983a163850c1ea4dbc5c6462e5b001e8d4/consumer/resolver_test.go#L7)):*
> ```Go
> 	"errors"
> 	"github.com/prometheus/client_golang/prometheus"
> 	dto "github.com/prometheus/client_model/go"
> ```

nit: separate includes. You might want to configure your editor to use `goimport`
___
*[consumer/resolver_test.go, line 94 at r2](https://reviewable.io/reviews/gazette/core/281#-MGUuLWV2237tjawn5Z7:-MGUuLWV2237tjawn5Z8:bzcd0ev) ([raw file](https://github.com/gazette/core/blob/cef37f983a163850c1ea4dbc5c6462e5b001e8d4/consumer/resolver_test.go#L94)):*
> ```Go
> 	}, resolve(ResolveArgs{ShardID: shardA, MayProxy: true}))
> 
> <<<<<<< HEAD
> ```

Just making sure you saw, some conflicts snuck in here. Otherwise this all looks great
___
*[mainboilerplate/runconsumer/run_consumer.go, line 10 at r2](https://reviewable.io/reviews/gazette/core/281#-MGUuUQ-8pJTT65sxRRi:-MGUuUQ-8pJTT65sxRRj:b-xfte7s) ([raw file](https://github.com/gazette/core/blob/cef37f983a163850c1ea4dbc5c6462e5b001e8d4/mainboilerplate/runconsumer/run_consumer.go#L10)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/prometheus/client_golang/prometheus"
> ```

nit: goimports ordering

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jgraettinger and @michaelschiff)

___
*[consumer/resolver_test.go, line 7 at r2](https://reviewable.io/reviews/gazette/core/281#-MGUu3nPClRf7DiCjHXv:-MGWkJus6t3yY0Vo50Kr:bujy86a) ([raw file](https://github.com/gazette/core/blob/cef37f983a163850c1ea4dbc5c6462e5b001e8d4/consumer/resolver_test.go#L7)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

nit: separate includes. You might want to configure your editor to use `goimport`
</blockquote></details>

fixed and updated my editor to default to `goimport` ordering
___
*[consumer/resolver_test.go, line 94 at r2](https://reviewable.io/reviews/gazette/core/281#-MGUuLWV2237tjawn5Z7:-MGWkDgp5fc8NJZi4qt0:bw6q29v) ([raw file](https://github.com/gazette/core/blob/cef37f983a163850c1ea4dbc5c6462e5b001e8d4/consumer/resolver_test.go#L94)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Just making sure you saw, some conflicts snuck in here. Otherwise this all looks great
</blockquote></details>

sorry, I should have caught that.  Fixed

**Review by jgraettinger — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: 2 of 4 files reviewed, all discussions resolved

**Review by jgraettinger — APPROVED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jgraettinger — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
