### PR TITLE
etcd grpc upgrade

### PR DESCRIPTION
**Pull request by michaelschiff**
This change is [Reviewable](https://reviewable.io/reviews/gazette/core/289)

### CODE REVIEW

**Review by jgraettinger — COMMENTED** [review]
Awesome, thanksT There are some in-advertent checked in test binaries, and import re-orders, but otherwise looks good

> Reviewed 45 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/289#-:-M_W2XME40kFcnDXRjcY:b-24tee0)* status: all files reviewed, 5 unresolved discussions (waiting on @michaelschiff)

___
*[allocator.test, line 0 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W019yE3fQIwfflSPU:-M_W019yE3fQIwfflSPV:b-3i25lt) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/allocator.test#L0)):*
back this out ?
___
*[ext.test, line 0 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W03s7CNRsqQtE0h0a:-M_W03s7CNRsqQtE0h0b:b-khmb8i) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/ext.test#L0)):*
this too? appears to be some test binaries that got checked in
___
*[allocator/allocator_key_space.go, line 6 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W0K8gEEcfUF5QiyLe:-M_W0K8gEEcfUF5QiyLf:b-8hdy4y) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/allocator/allocator_key_space.go#L6)):*
> ```Go
> 	"bytes"
> 	"fmt"
> 	"go.etcd.io/etcd/api/v3/mvccpb"
> ```

nit: ordering
___
*[allocator/allocator_key_space_test.go, line 7 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W0MKVDkfdd_-4SEY2:-M_W0MKVDkfdd_-4SEY3:b-obcwzc) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/allocator/allocator_key_space_test.go#L7)):*
> ```Go
> 	"encoding/json"
> 	"fmt"
> 	"go.etcd.io/etcd/api/v3/mvccpb"
> ```

here too, and elsewhere
___
*[broker/protocol/dispatcher.go, line 102 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W0qcXE7ekpFAgRr4Q:-M_W0qcXE7ekpFAgRr4R:brt26hd) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/broker/protocol/dispatcher.go#L102)):*
> ```Go
> 
> func (d *dispatcher) ResolverError(_ error) {
> 	//TODO:(johnny/michaelschiff): im not sure if we should be handling this. HandleResolvedAddrs in the
> ```

Skimming docs, it appears that `UpdateClientConnState` and `ResolverError` are effectively a de-structuring of the former `HandleResolvedAddrs`.

If you agreed, could you please preserve the comment from HandledResolvedAddrs ? I continue to think these are no-ops but we should keep documented _why_ they're no-ops.

**Review by jgraettinger — COMMENTED** [review]
thanks, LGTM

> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/289#-:-M_WmHVtCHxHYy6tlN_E:b9i5hkm)* status: all files reviewed, 5 unresolved discussions (waiting on @michaelschiff)

**Review by jgraettinger — COMMENTED** [review]
Whoops, the dispatcher.go comment is still open, but otherwise I'm happy.
Is anything else in process on your end before merging?

We should be careful to squash this before landing it so that the binaries don't make their way into the `master` branch commit history.

> *[Reviewable](https://reviewable.io/reviews/gazette/core/289#-:-M_WmfI61R3bdcweVi10:b-sgxpgm)* status: all files reviewed, 5 unresolved discussions (waiting on @michaelschiff)

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/289)* status: 41 of 46 files reviewed, 4 unresolved discussions (waiting on @jgraettinger)

___
*[allocator.test, line  at r1](https://reviewable.io/reviews/gazette/core/289#-M_W019yE3fQIwfflSPU:-M_vqcac7ee4M6yiQqUH:b-896fix) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/allocator.test#L)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

back this out ?
</blockquote></details>

Done.
___
*[ext.test, line  at r1](https://reviewable.io/reviews/gazette/core/289#-M_W03s7CNRsqQtE0h0a:-M_vqdT0CxJPAouvig-O:b-896fix) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/ext.test#L)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

this too? appears to be some test binaries that got checked in
</blockquote></details>

Done.
___
*[allocator/allocator_key_space_test.go, line 7 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W0MKVDkfdd_-4SEY2:-M_vqhi_2IdzkHc4jbUx:b-896fix) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/allocator/allocator_key_space_test.go#L7)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

here too, and elsewhere
</blockquote></details>

Done.
___
*[broker/protocol/dispatcher.go, line 102 at r1](https://reviewable.io/reviews/gazette/core/289#-M_W0qcXE7ekpFAgRr4Q:-M_vqk-rClTYS8dbZlOy:b-896fix) ([raw file](https://github.com/gazette/core/blob/9a53f0b8f903bb994212ea5bf7ec046a9496045d/broker/protocol/dispatcher.go#L102)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Skimming docs, it appears that `UpdateClientConnState` and `ResolverError` are effectively a de-structuring of the former `HandleResolvedAddrs`.

If you agreed, could you please preserve the comment from HandledResolvedAddrs ? I continue to think these are no-ops but we should keep documented _why_ they're no-ops.
</blockquote></details>

Done.

**Review by jgraettinger — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michaelschiff)

**Review by jgraettinger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michaelschiff)

**Pull request merged**
