### PR TITLE
Azure store

### PR DESCRIPTION
**Pull request by michaelschiff**
Implements `fragment.backend` for azure using `github.com/Azure/azure-storage-blob-go`. Additional required configuration for `azureBackend` is setting two new environment variables `AZURE_ACCOUNT_NAME` and `AZURE_ACCOUNT_KEY` (similar to configuration of `GOOGLE_APPLICATION_CREDENTIALS` for `gcsBackend`)

This change is [Reviewable](https://reviewable.io/reviews/gazette/core/287)

### CODE REVIEW

**Review by jgraettinger — CHANGES_REQUESTED** [review]
Thanks for this! And sorry for the delay. A few comments below

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287#-:-MYFYODB1PY8TrpMWF9n:b-4a78k7)* status: all files reviewed, 5 unresolved discussions (waiting on @michaelschiff)

___
*[broker/fragment/store_azure.go, line 45 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFT_lqEuGa7V5WK5Yd:-MYFT_lqEuGa7V5WK5Ye:beyad8f) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L45)):*
> ```Go
> 	sasQueryParams, err := azblob.BlobSASSignatureValues{
> 		Protocol:      azblob.SASProtocolHTTPS,                     // Users MUST use HTTPS (not HTTP)
> 		ExpiryTime:    time.Now().UTC().Add(48 * time.Hour), // 48-hours before expiration
> ```

Use the passed-in `time.Duration` with `time.Now` to build the `ExpiryTime`.

(also was this `go fmt`'d ? comments don't line up in the usual way).
___
*[broker/fragment/store_azure.go, line 72 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFUauNDoeOFjIA75mP:-MYFUauNDoeOFjIA75mQ:b-irq2oo) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L72)):*
> ```Go
> 	if _, err = blobURL.GetProperties(ctx, azblob.BlobAccessConditions{}, azblob.ClientProvidedKeyOptions{}); err == nil {
> 		return true, nil
> 	} else {
> ```

nit: else {} nesting isn't necessary and can be flattened.
___
*[broker/fragment/store_azure.go, line 77 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFUpOTC2ED_VtKPBxj:-MYFUpOTC2ED_VtKPBxk:b-7x2ssz) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L77)):*
> ```Go
> 			return false, err
> 		}
> 		errCode := storageErr.ServiceCode()
> ```

nit: `if storageErr.ServiceCode() == azblob.ServiceCodeBlobNotFound { ` ?

You're not using `errCode` except for this comparison.
___
*[broker/fragment/store_azure.go, line 90 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFVe4rDrBMw_iYrEK-:-MYFVe4rDrBMw_iYrEK0:boxmf2j) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L90)):*
> ```Go
> 		return nil, err
> 	}
> 	u, err := url.Parse(fmt.Sprint(a.endpoint, cfg.bucket, "/", cfg.rewritePath(cfg.prefix, fragment.ContentPath())))
> ```

nit: building `blobURL` in this exact way is repeated several times, hoist to a helper function ?
___
*[broker/fragment/store_azure.go, line 99 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFWHzxCvxGn3Larc7T:-MYFWHzxCvxGn3Larc7U:b-nikqv5) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L99)):*
> ```Go
> 		return nil, err
> 	}
> 	return download.Body(azblob.RetryReaderOptions{MaxRetryRequests: 20}), nil
> ```

This result is going to be wrapped in a `client.RetryReader`.
We probably want just one place where retries are being done,
and I'd suggest that this _shouldn't_ retry.

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @jgraettinger and @michaelschiff)

___
*[broker/fragment/store_azure.go, line 45 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFT_lqEuGa7V5WK5Yd:-MYHtmZWBXPUun3ke0FS:b-bkdnmk) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L45)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Use the passed-in `time.Duration` with `time.Now` to build the `ExpiryTime`.

(also was this `go fmt`'d ? comments don't line up in the usual way).
</blockquote></details>

ah nope I must have screwed up my format on save settings
___
*[broker/fragment/store_azure.go, line 99 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFWHzxCvxGn3Larc7T:-MYHtjGp13xPVPv89szu:b-e8513m) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L99)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

This result is going to be wrapped in a `client.RetryReader`.
We probably want just one place where retries are being done,
and I'd suggest that this _shouldn't_ retry.
</blockquote></details>

good point

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jgraettinger)

___
*[broker/fragment/store_azure.go, line 45 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFT_lqEuGa7V5WK5Yd:-MYHuWhy0QwArmrOIm7A:b-896fix) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L45)):*
<details><summary><i>Previously, michaelschiff wrote…</i></summary><blockquote>

ah nope I must have screwed up my format on save settings
</blockquote></details>

Done.
___
*[broker/fragment/store_azure.go, line 99 at r1](https://reviewable.io/reviews/gazette/core/287#-MYFWHzxCvxGn3Larc7T:-MYHuy3k66SLnCXYNPNC:b-896fix) ([raw file](https://github.com/gazette/core/blob/30ac1201db1456f7e67dbce67300b76d12e3455d/broker/fragment/store_azure.go#L99)):*
<details><summary><i>Previously, michaelschiff wrote…</i></summary><blockquote>

good point 
</blockquote></details>

Done.

**Review by jgraettinger — APPROVED** [review]
LGTM % the extra debug logging

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287#-:-MYKV625AIrzK4DrXNgd:b-tpe0r3)* status: all files reviewed, 1 unresolved discussion (waiting on @michaelschiff)

___
*[broker/fragment/store_azure.go, line 46 at r2](https://reviewable.io/reviews/gazette/core/287#-MYKUxW78b5NkRYszWIG:-MYKUxW78b5NkRYszWIH:b-hqiz5m) ([raw file](https://github.com/gazette/core/blob/85150c683a1f57844c9202f61b9566513f5deb50/broker/fragment/store_azure.go#L46)):*
> ```Go
> 	}
> 	blobName := cfg.rewritePath(cfg.prefix, fragment.ContentPath())
> 	log.Println(d)
> ```

left-over debug logging ?

**Review by michaelschiff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jgraettinger)

___
*[broker/fragment/store_azure.go, line 46 at r2](https://reviewable.io/reviews/gazette/core/287#-MYKUxW78b5NkRYszWIG:-MYLVX2O5rV0ZNjAI-_s:b-a1kx7c) ([raw file](https://github.com/gazette/core/blob/85150c683a1f57844c9202f61b9566513f5deb50/broker/fragment/store_azure.go#L46)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

left-over debug logging ?
</blockquote></details>

oof yes removed

**Review by jgraettinger — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gazette/core/287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michaelschiff)

**Pull request merged**
